# Flags
# =====
REPO ?= /home/bruno/devel/florence/lc3

# Config macros passed to bsc
# ===========================
BSC_COMPILATION_FLAGS +=

# Common boilerplate rules
# ========================
include $(REPO)/builds/Resources/Include_Common.mk

# Makefile rules for simulator: bluesim
# ======================================
include $(REPO)/builds/Resources/Include_bluesim.mk
